### ISSUE TITLE
Unexpected token line 54

### ISSUE THREAD

**Issue by mlumbroso** [aksonov/react-native-mobx#4]
Hello,

thanks for all the code you provide for the open source community :-)

Trying to reproduce the example, I encountered this issue :
`index.js : unexpected token (54:0)`

which corresponds to `@observer` declaration. I'm using RN 0.27.2

Any thoughts? I've got the same error if I try to insert an @observer somewhere else.

Thanks

EDIT : Actually it's every @ declaration (`@action`, `@observer`...), it's like I can't use ES6 syntax, any specific configuration to do to use it?

**Comment by mastermoo** [comment]
You need to install these packages:
1. autobind-decorator
2. babel-preset-react-native-stage-0

And you need to add this file to your project, [.babelrc](https://github.com/aksonov/react-native-mobx/blob/master/Example/.babelrc)

**Comment by mlumbroso** [comment]
Thanks, that solves it !
